import { NextResponse } from "next/server";
import { getCampaign, getCampaignLock, listCampaigns, saveCampaign, logCampaignDebug } from "@/lib/campaign/store";
import { createId } from "@/lib/utils/ids";
import { runDungeonMaster, runProfileGeneration, waitForDmIdle, serverLog, serverError } from "@/lib/aqua/chat";

export const dynamic = "force-dynamic";

export async function POST(request: Request) {
  const body = await request.json().catch(() => ({}));
  const code = String(body.joinCode || "").trim().toUpperCase();
  const name = String(body.name || "Player").trim() || "Player";
  const characterName = String(body.characterName || "").trim();
  const background = String(body.background || "").trim();
  const personality = String(body.personality || "").trim();
  
  serverLog("API join", `Player '${name}' requesting to join campaign code/id '${code}' | Character: '${characterName}'`);
  
  const campaigns = await listCampaigns();
  const summary = campaigns.find((campaign) => campaign.joinCode === code || campaign.id === code);
  if (!summary) {
    serverLog("API join", `Join rejected: Campaign not found for code/id '${code}'`);
    return NextResponse.json({ error: "Campaign not found" }, { status: 404 });
  }

  let isReleased = false;
  const release = await getCampaignLock(summary.id).acquire();
  const safeRelease = () => {
    if (!isReleased) {
      isReleased = true;
      release();
    }
  };

  try {
    const campaign = await getCampaign(summary.id);
    
    const hasStoryStarted = campaign.displayEvents.some(
      (e) => e.type === "narration" || e.type === "dialogue"
    );
    const isInitialStarting = campaign.status === "active" && !hasStoryStarted;
    if (isInitialStarting) {
      serverLog("API join", `Join rejected: Campaign '${campaign.title}' is currently starting.`);
      return NextResponse.json({ error: "The campaign is currently starting. Please wait until the opening scenario is ready." }, { status: 400 });
    }

    let player = campaign.players.find((item) => item.name.toLowerCase() === name.toLowerCase());
    const isNewPlayer = !player;
    if (!player) {
      player = { 
        id: createId("player"), 
        name, 
        characterName: characterName || undefined, 
        background: background || undefined, 
        personality: personality || undefined,
        joinedAt: new Date().toISOString(), 
        inventory: [], 
        abilities: [], 
        notes: "",
        status: "Generating profile...",
        stats: [
          { name: "HP", value: 20, maxValue: 20, color: "red" }
        ]
      };
      campaign.players.push(player);
    } else {
      if (characterName) player.characterName = characterName;
      if (background) player.background = background;
      if (personality) player.personality = personality;
      // An explicit rejoin ends the absence: the rejoin turn below weaves them
      // back in, so the presence sweep must not re-run a return weave later.
      player.away = false;
      player.wovenOut = false;
    }

    if (!campaign.partyLeaderId) campaign.partyLeaderId = player.id;
    await saveCampaign(campaign);

    if (isNewPlayer) {
      // Release HTTP request lock
      safeRelease();

      // Trigger DM portrait generation and sheet setup in background with retries
      (async () => {
        const maxTries = 3;
        let success = false;
        let lastError: any = null;

        for (let attempt = 1; attempt <= maxTries; attempt++) {
          const bgRelease = await getCampaignLock(campaign.id).acquire();
          try {
            await logCampaignDebug(campaign.id, `[Join Attempt ${attempt}/${maxTries}] Starting background profile generation...`);
            serverLog("API join background", `Attempt ${attempt}/${maxTries} - Initiating profile generation for player: ${player!.name}`);
            
            // Re-fetch to ensure fresh data and check if already generated by another parallel process
            const currentCampaign = await getCampaign(campaign.id);
            const p = currentCampaign.players.find(item => item.id === player!.id);
            if (p) {
              // Don't stomp a good profile back to "Generating profile..." on a
              // retry: if a prior attempt already produced a portrait, the sheet
              // is effectively complete and runProfileGeneration will finalize it.
              if (!p.portraitUrl) p.status = "Generating profile...";
              currentCampaign.dmStatus = `Forging character sheet... (Attempt ${attempt}/${maxTries})`;
              currentCampaign.dmPhase = "sheet";
              await saveCampaign(currentCampaign);
            }

            // Call runProfileGeneration in chat.ts
            await runProfileGeneration(campaign.id, player!.id);
            
            // Verify if character sheet was successfully updated. We accept a
            // generation as successful when EITHER the status flipped away from
            // "Generating profile..." OR a portrait was produced AND at least
            // one sheet detail (notes/inventory/abilities) was filled in. This
            // avoids false negatives when the model omits the status field but
            // still produced a complete sheet.
            const verifiedCampaign = await getCampaign(campaign.id);
            const verifiedPlayer = verifiedCampaign.players.find(item => item.id === player!.id);
            if (verifiedPlayer) {
              const statusFlipped = verifiedPlayer.status !== "Generating profile..." && !/^error/i.test(verifiedPlayer.status || "");
              const hasPortrait = !!verifiedPlayer.portraitUrl;
              const hasSheetDetails = !!(verifiedPlayer.notes || (Array.isArray(verifiedPlayer.inventory) && verifiedPlayer.inventory.length > 0) || (Array.isArray(verifiedPlayer.abilities) && verifiedPlayer.abilities.length > 0));
              const verified = statusFlipped || (hasPortrait && hasSheetDetails);
              if (verified) {
                // Ensure status is never left on "Generating profile..." when
                // the sheet is actually complete (model omitted status field).
                if (!statusFlipped) {
                  verifiedPlayer.status = "Ready";
                  await saveCampaign(verifiedCampaign);
                }
                success = true;
                await logCampaignDebug(campaign.id, `[Join Attempt ${attempt}/${maxTries}] Succeeded and verified.`);
                serverLog("API join background", `Attempt ${attempt}/${maxTries} - Profile generation succeeded for player: ${player!.name}`);
                
              // If active, integrate them into the scene
              if (verifiedCampaign.status === "active") {
                await logCampaignDebug(campaign.id, `[Join Active Integration] Splicing new character into the live scene.`);
                serverLog("API join background", `Integrating player ${verifiedPlayer.characterName || verifiedPlayer.name} into the active campaign.`);
                
                const integrateMessage = [
                  `A new player has joined the active game!`,
                  verifiedCampaign.campaignType === "dnd"
                    ? `Campaign type: Dungeons & Dragons (${verifiedCampaign.rulesMode === "full" ? "full 5e rules" : "rules-light D&D"}).`
                    : `Campaign type: standard tabletop RPG, not D&D. Preserve the current genre and do not add fantasy/D&D assumptions unless already present.`,
                  `- Character Name: ${verifiedPlayer.characterName || verifiedPlayer.name}`,
                  `- Background: ${verifiedPlayer.background || "None"}`,
                  `- Personality: ${verifiedPlayer.personality || "None"}`,
                  `Do these steps in order:`,
                  `1. Briefly weave their entry into the current scene.`,
                  `2. Provide starting playerActions for them.`,
                  `3. Reuse the current background unless a new image is clearly needed.`
                ].join("\n");
                
                // Wait for the table to be genuinely idle — generation
                // finished, the TV done playing out the previous turn's beats,
                // no half-locked exploration round — so a new arrival never
                // interrupts a story beat in flight (feedback #7).
                await waitForDmIdle(campaign.id);
                await runDungeonMaster(campaign.id, verifiedPlayer.name, integrateMessage, { hiddenUserMessage: true });
              }

              bgRelease();
              break;
              } else {
                const missing: string[] = [];
                if (!hasPortrait) missing.push("portrait");
                if (!hasSheetDetails) missing.push("sheet details (notes/inventory/abilities)");
                if (statusFlipped) missing.push("status still 'Generating profile...'");
                throw new Error(`Profile generation incomplete — missing: ${missing.join(", ") || "unknown"}`);
              }
            } else {
              throw new Error("Profile generation completed but the player record could not be found for verification");
            }
          } catch (err) {
            lastError = err;
            serverError("API join background", `Attempt ${attempt}/${maxTries} - Profile generation failed for player: ${player!.name}`, err);
            await logCampaignDebug(campaign.id, `[Join Attempt ${attempt}/${maxTries}] Failed: ${err instanceof Error ? err.message : String(err)}`);
          } finally {
            bgRelease();
          }

          if (attempt < maxTries) {
            await new Promise(resolve => setTimeout(resolve, 3000));
          }
        }

        if (!success) {
          const bgRelease = await getCampaignLock(campaign.id).acquire();
          try {
            const finalCampaign = await getCampaign(campaign.id);
            const finalPlayer = finalCampaign.players.find(item => item.id === player!.id);
            if (finalPlayer) {
              finalPlayer.status = `Error: Character generation failed after ${maxTries} attempts.`;
              finalPlayer.notes = `${lastError instanceof Error ? lastError.message : String(lastError)}`;
              finalCampaign.dmStatus = undefined; // Clear DM thinking status
              finalCampaign.dmPhase = undefined;
              await saveCampaign(finalCampaign);
              await logCampaignDebug(campaign.id, `[Join Final Failure] Character generation aborted after maximum attempts.`);
              serverError("API join background", `Profile generation completely failed for player: ${player!.name} after ${maxTries} attempts.`);
            }
          } catch (err) {
            serverError("API join background", "Failed to set error status on player", err);
          } finally {
            bgRelease();
          }
        }
      })();

      return NextResponse.json({ campaignId: campaign.id, player, isPartyLeader: campaign.partyLeaderId === player.id });
    } else {
      if (campaign.status === "active") {
        const rejoinMessage = [
          `Player ${player.characterName || player.name} has rejoined the game after being disconnected!`,
          campaign.campaignType === "dnd"
            ? `Campaign type: Dungeons & Dragons (${campaign.rulesMode === "full" ? "full 5e rules" : "rules-light D&D"}).`
            : `Campaign type: standard tabletop RPG, not D&D. Preserve the current genre and do not add fantasy/D&D assumptions unless already present.`,
          `Do these steps in order:`,
          `1. Briefly weave their return into the current scene.`,
          `2. Set their status to Active or Ready.`,
          `3. Provide fresh playerActions for them and other active players.`,
          `4. Reuse the current background unless a new image is clearly needed.`
        ].join("\n");

        // Release HTTP request lock
        safeRelease();

        // Trigger DM rejoin processing in background
        (async () => {
          // Wait for the table to be genuinely idle before weaving a return,
          // mirroring the departure/return path in the party sweep — a rejoin
          // must not talk over a story beat in flight (feedback #7).
          await waitForDmIdle(campaign.id);
          const bgRelease = await getCampaignLock(campaign.id).acquire();
          try {
            serverLog("API join background", `Initiating background rejoin handling for player: ${player.characterName || player.name}`);
            await runDungeonMaster(campaign.id, player!.name, rejoinMessage, { hiddenUserMessage: true });
            serverLog("API join background", `Rejoin handling completed for player: ${player.characterName || player.name}`);
          } catch (err) {
            serverError("API join background", `Background Dungeon Master rejoin processing failed for player: ${player.characterName || player.name}`, err);
          } finally {
            bgRelease();
          }
        })();

        return NextResponse.json({ campaignId: campaign.id, player, isPartyLeader: campaign.partyLeaderId === player.id });
      }
    }

    return NextResponse.json({ campaignId: campaign.id, player, isPartyLeader: campaign.partyLeaderId === player.id });
  } finally {
    safeRelease();
  }
}
